sudo: required
services:
  - docker # Docker needs to be pre-installed on the running container

before_install: # steps to execute before running test
  - docker build -t docker-k8s-course/docker-react -f Dockerfile.dev .

script: # a series of commands to run test
  - docker run -t docker-k8s-course/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-618101950088"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
